language: php

php:
  - 7.4

sudo: false

before_script:
  - composer install

script: 
  - php vendor/bin/phpbench run --report=all --progress=travis
  - php vendor/bin/phpbench run --report=all --output=html
